// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/community" | "/community/discussion/[id]" | "/community/guidelines" | "/community/new" | "/community/tags" | "/curriculum" | "/curriculum/[slug]" | "/curriculum/[slug]/lesson/[lessonId]" | "/curriculum/[slug]/quiz/[quizId]" | "/focus" | "/jobs" | "/jobs/[id]" | "/leaderboard" | "/playground" | "/playground/sandbox" | "/pricing" | "/profile" | "/projects" | "/settings/billing" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]" | "/tracks"
type AppRouteHandlerRoutes = "/api/v1/admin/data-layer/setup" | "/api/v1/cloudinary/sign" | "/api/v1/community/leaderboard" | "/api/v1/community/tags" | "/api/v1/community/threads" | "/api/v1/community/threads/[threadId]" | "/api/v1/community/threads/[threadId]/comments" | "/api/v1/community/votes" | "/api/v1/courses" | "/api/v1/courses/[courseId]" | "/api/v1/courses/[courseId]/lessons/[lessonId]" | "/api/v1/courses/[courseId]/quizzes/[quizId]" | "/api/v1/courses/[courseId]/quizzes/[quizId]/attempts" | "/api/v1/courses/[courseId]/syllabus" | "/api/v1/dashboard/home" | "/api/v1/enrollments" | "/api/v1/integrations/health" | "/api/v1/leads/newsletter" | "/api/v1/me" | "/api/v1/notifications" | "/api/v1/notifications/[notificationId]/read" | "/api/v1/playground/sessions" | "/api/v1/playground/sessions/[sessionId]" | "/api/v1/playground/sessions/[sessionId]/files" | "/api/v1/playground/sessions/[sessionId]/run" | "/api/v1/playground/sessions/[sessionId]/runs" | "/api/v1/playground/templates" | "/api/v1/profile/overview" | "/api/v1/profile/preferences" | "/api/v1/progress" | "/api/v1/projects" | "/api/v1/projects/[projectId]" | "/api/v1/projects/[projectId]/submissions/me"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/v1/admin/data-layer/setup": {}
  "/api/v1/cloudinary/sign": {}
  "/api/v1/community/leaderboard": {}
  "/api/v1/community/tags": {}
  "/api/v1/community/threads": {}
  "/api/v1/community/threads/[threadId]": { "threadId": string; }
  "/api/v1/community/threads/[threadId]/comments": { "threadId": string; }
  "/api/v1/community/votes": {}
  "/api/v1/courses": {}
  "/api/v1/courses/[courseId]": { "courseId": string; }
  "/api/v1/courses/[courseId]/lessons/[lessonId]": { "courseId": string; "lessonId": string; }
  "/api/v1/courses/[courseId]/quizzes/[quizId]": { "courseId": string; "quizId": string; }
  "/api/v1/courses/[courseId]/quizzes/[quizId]/attempts": { "courseId": string; "quizId": string; }
  "/api/v1/courses/[courseId]/syllabus": { "courseId": string; }
  "/api/v1/dashboard/home": {}
  "/api/v1/enrollments": {}
  "/api/v1/integrations/health": {}
  "/api/v1/leads/newsletter": {}
  "/api/v1/me": {}
  "/api/v1/notifications": {}
  "/api/v1/notifications/[notificationId]/read": { "notificationId": string; }
  "/api/v1/playground/sessions": {}
  "/api/v1/playground/sessions/[sessionId]": { "sessionId": string; }
  "/api/v1/playground/sessions/[sessionId]/files": { "sessionId": string; }
  "/api/v1/playground/sessions/[sessionId]/run": { "sessionId": string; }
  "/api/v1/playground/sessions/[sessionId]/runs": { "sessionId": string; }
  "/api/v1/playground/templates": {}
  "/api/v1/profile/overview": {}
  "/api/v1/profile/preferences": {}
  "/api/v1/progress": {}
  "/api/v1/projects": {}
  "/api/v1/projects/[projectId]": { "projectId": string; }
  "/api/v1/projects/[projectId]/submissions/me": { "projectId": string; }
  "/community": {}
  "/community/discussion/[id]": { "id": string; }
  "/community/guidelines": {}
  "/community/new": {}
  "/community/tags": {}
  "/curriculum": {}
  "/curriculum/[slug]": { "slug": string; }
  "/curriculum/[slug]/lesson/[lessonId]": { "slug": string; "lessonId": string; }
  "/curriculum/[slug]/quiz/[quizId]": { "slug": string; "quizId": string; }
  "/focus": {}
  "/jobs": {}
  "/jobs/[id]": { "id": string; }
  "/leaderboard": {}
  "/playground": {}
  "/playground/sandbox": {}
  "/pricing": {}
  "/profile": {}
  "/projects": {}
  "/settings/billing": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
  "/tracks": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
