// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/community/discussion/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/discussion/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/community/discussion/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/guidelines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/guidelines">> = Specific
  const handler = {} as typeof import("../../src/app/community/guidelines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/new">> = Specific
  const handler = {} as typeof import("../../src/app/community/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community">> = Specific
  const handler = {} as typeof import("../../src/app/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/community/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/tags">> = Specific
  const handler = {} as typeof import("../../src/app/community/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/curriculum/[slug]/lesson/[lessonId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/curriculum/[slug]/lesson/[lessonId]">> = Specific
  const handler = {} as typeof import("../../src/app/curriculum/[slug]/lesson/[lessonId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/curriculum/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/curriculum/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/curriculum/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/curriculum/[slug]/quiz/[quizId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/curriculum/[slug]/quiz/[quizId]">> = Specific
  const handler = {} as typeof import("../../src/app/curriculum/[slug]/quiz/[quizId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/curriculum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/curriculum">> = Specific
  const handler = {} as typeof import("../../src/app/curriculum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/focus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/focus">> = Specific
  const handler = {} as typeof import("../../src/app/focus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/playground/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playground">> = Specific
  const handler = {} as typeof import("../../src/app/playground/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/playground/sandbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playground/sandbox">> = Specific
  const handler = {} as typeof import("../../src/app/playground/sandbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../src/app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/billing">> = Specific
  const handler = {} as typeof import("../../src/app/settings/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-in/[[...sign-in]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../src/app/sign-in/[[...sign-in]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/[[...sign-up]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/[[...sign-up]]">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/[[...sign-up]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tracks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tracks">> = Specific
  const handler = {} as typeof import("../../src/app/tracks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/admin/data-layer/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/data-layer/setup">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/admin/data-layer/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/cloudinary/sign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/cloudinary/sign">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/cloudinary/sign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/community/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/community/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/community/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/community/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/community/tags">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/community/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/community/threads/[threadId]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/community/threads/[threadId]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/community/threads/[threadId]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/community/threads/[threadId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/community/threads/[threadId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/community/threads/[threadId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/community/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/community/threads">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/community/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/community/votes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/community/votes">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/community/votes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/courses/[courseId]/lessons/[lessonId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/courses/[courseId]/lessons/[lessonId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/courses/[courseId]/lessons/[lessonId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/courses/[courseId]/quizzes/[quizId]/attempts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/courses/[courseId]/quizzes/[quizId]/attempts">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/courses/[courseId]/quizzes/[quizId]/attempts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/courses/[courseId]/quizzes/[quizId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/courses/[courseId]/quizzes/[quizId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/courses/[courseId]/quizzes/[quizId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/courses/[courseId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/courses/[courseId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/courses/[courseId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/courses/[courseId]/syllabus/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/courses/[courseId]/syllabus">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/courses/[courseId]/syllabus/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/courses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/courses">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/dashboard/home/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/dashboard/home">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/dashboard/home/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/enrollments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/enrollments">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/enrollments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/integrations/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/integrations/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/integrations/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/leads/newsletter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/leads/newsletter">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/leads/newsletter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/notifications/[notificationId]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/notifications/[notificationId]/read">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/notifications/[notificationId]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/playground/sessions/[sessionId]/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/playground/sessions/[sessionId]/files">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/playground/sessions/[sessionId]/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/playground/sessions/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/playground/sessions/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/playground/sessions/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/playground/sessions/[sessionId]/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/playground/sessions/[sessionId]/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/playground/sessions/[sessionId]/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/playground/sessions/[sessionId]/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/playground/sessions/[sessionId]/runs">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/playground/sessions/[sessionId]/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/playground/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/playground/sessions">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/playground/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/playground/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/playground/templates">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/playground/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/profile/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/profile/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/profile/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/profile/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/profile/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/profile/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/progress">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/projects/[projectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/projects/[projectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/projects/[projectId]/submissions/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/projects/[projectId]/submissions/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/projects/[projectId]/submissions/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
